package entities;
// Generated May 26, 2017 4:47:57 PM by Hibernate Tools 5.2.3.Final

/**
 * Flightinfo generated by hbm2java
 */
@Entity
@Table(name = "flightinfo", catalog = "flight")
@XmlRootElement(name="flightinfo")
public class Flightinfo implements java.io.Serializable {

	private Integer id;
	private String originAirport;
	private String destinationAirport;
	private String departureTime;
	private String arrivalTime;
	private String flightNumber;
	private String carrierName;

	public Flightinfo() {
	}

	public Flightinfo(String originAirport, String destinationAirport, String departureTime, String arrivalTime,
			String flightNumber, String carrierName) {
		this.originAirport = originAirport;
		this.destinationAirport = destinationAirport;
		this.departureTime = departureTime;
		this.arrivalTime = arrivalTime;
		this.flightNumber = flightNumber;
		this.carrierName = carrierName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOriginAirport() {
		return this.originAirport;
	}

	public void setOriginAirport(String originAirport) {
		this.originAirport = originAirport;
	}

	public String getDestinationAirport() {
		return this.destinationAirport;
	}

	public void setDestinationAirport(String destinationAirport) {
		this.destinationAirport = destinationAirport;
	}

	public String getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime;
	}

	public String getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	public String getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public String getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

}
